### ISSUE TITLE
Zephyr support

### ISSUE THREAD

**Issue by ikerperezdelpalomar** [CodethinkLabs/bloodlight-firmware#116]
- [x] Run Zephyr in bloodlight board #110
- [x] Add basic devicetree support #111
- [ ] Make sure the peripherals are controllable with Zephyr #112
- [ ] Add support for reading ADCs using Zephyr #113
- [ ] Set up DMA in zephyr for bloodlight board #114
- [ ] Migrate Bloodlight functionality to Zephyr #115

**Comment by ikerperezdelpalomar** [comment]
See: https://github.com/ikerperezdelpalomar/zephyr/commits/bloodlight

**Comment by tlsa** [comment]
Moved to here: https://github.com/CodethinkLabs/bloodlight-zephyr
